#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

#enable_downloads=$(ynh_app_setting_get --app=$app --key=enable_downloads)
#scanner_extractor=$(ynh_app_setting_get --app=$app --key=scanner_extractor)
#enable_animation=$(ynh_app_setting_get --app=$app --key=enable_animation)
#enable_transcoding=$(ynh_app_setting_get --app=$app --key=enable_transcoding)
#welcome_message=$(ynh_app_setting_get --app=$app --key=welcome_message)
#enable_sharing=$(ynh_app_setting_get --app=$app --key=enable_sharing)

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Modifying a config file..." --weight=1

config_path="/var/lib/$app"
path_url="$new_path"

ynh_add_config --template="../conf/navidrome.toml" --destination="$config_path/navidrome.toml"

chmod 600 "$config_path/navidrome.toml"
chown -R $app:$app "$config_path"

#=================================================
# GENERIC FINALISATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path=systemd --line_match="Version:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
