#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

scanner_extractor="taglib"
enable_downloads="true"
enable_animation="true"
enable_transcoding="false"
welcome_message=""
enable_sharing="false"

ynh_app_setting_set --key=enable_downloads --value=$enable_downloads
ynh_app_setting_set --key=scanner_extractor --value=$scanner_extractor
ynh_app_setting_set --key=enable_animation --value=$enable_animation
ynh_app_setting_set --key=enable_transcoding --value=$enable_transcoding
ynh_app_setting_set --key=welcome_message --value=$welcome_message
ynh_app_setting_set --key=enable_sharing --value=$enable_sharing

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/navidrome"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="navidrome.toml" --destination="$data_dir/navidrome.toml"

chmod 600 "$data_dir/navidrome.toml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Music collection server and streamer" --log="/var/log/$app/$app.log"

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

ynh_multimedia_build_main_dir

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
