#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

scanner_extractor="taglib"
enable_downloads="true"
enable_animation="true"
enable_transcoding="false"
welcome_message=""
enable_sharing="false"
config_path="/var/lib/$app"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=enable_downloads --value=$enable_downloads
ynh_app_setting_set --key=scanner_extractor --value=$scanner_extractor
ynh_app_setting_set --key=enable_animation --value=$enable_animation
ynh_app_setting_set --key=enable_transcoding --value=$enable_transcoding
ynh_app_setting_set --key=welcome_message --value=$welcome_message
ynh_app_setting_set --key=enable_sharing --value=$enable_sharing
ynh_app_setting_set --key=config_path --value=$config_path

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$config_path"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="Web-based music collection server and streamer" --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

ynh_multimedia_build_main_dir

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# Main config File
ynh_config_add --template="navidrome.toml" --destination="$config_path/navidrome.toml"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 600 "$config_path/navidrome.toml"
chown -R $app:$app "$config_path"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Version:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
