#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

if ynh_exec_warn_less yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_remove_systemd_config

ynh_remove_nginx_config

ynh_secure_remove --file="/var/lib/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
