#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_safe_rm "/var/lib/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
