#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path=systemd

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

if [ -z "${language:-}" ]; then
	language="en"
	ynh_app_setting_set --app=$app --key=language --value=$language
fi

if [ -z "${enable_animation:-}" ]; then
	enable_animation="true"
	ynh_app_setting_set --app=$app --key=enable_animation --value=$enable_animation
fi

if [ -z "${enable_downloads:-}" ]; then
	enable_downloads="true"
	ynh_app_setting_set --app=$app --key=enable_downloads --value=$enable_downloads
fi

if [ -z "${scanner_extractor:-}" ]; then
	scanner_extractor="taglib"
	ynh_app_setting_set --app=$app --key=scanner_extractor --value=$scanner_extractor
fi

if [ -z "${enable_transcoding:-}" ]; then
	enable_transcoding="false"
	ynh_app_setting_set --app=$app --key=enable_transcoding --value=$enable_transcoding
fi

if [ -z "${welcome_message:-}" ]; then
	welcome_message=""
	ynh_app_setting_set --app=$app --key=welcome_message --value=$welcome_message
fi

if [ -z "${enable_sharing:-}" ]; then
	enable_sharing="false"
	ynh_app_setting_set --app=$app --key=enable_sharing --value=$enable_sharing
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=5

	# Remove the app directory securely
	ynh_secure_remove --file=$install_dir

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --source_id=$YNH_ARCH
fi

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=5

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Web-based music collection server and streamer"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..."

config_path="/var/lib/$app"

# Uncomment when there is new options added upstream
ynh_add_config --template="../conf/navidrome.toml" --destination="$config_path/navidrome.toml"

chmod 600 "$config_path/navidrome.toml"
chown -R $app:$app "$config_path"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path=systemd --line_match="Version:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
