#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path=systemd

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=language --value="en"
ynh_app_setting_set_default --key=enable_animation --value="true"
ynh_app_setting_set_default --key=enable_downloads --value="true"
ynh_app_setting_set_default --key=scanner_extractor --value="taglib"
ynh_app_setting_set_default --key=enable_transcoding --value="false"
ynh_app_setting_set_default --key=welcome_message --value=""
ynh_app_setting_set_default --key=enable_sharing --value="false"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Web-based music collection server and streamer" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating configuration..."

# Uncomment when there is new options added upstream
#ynh_config_add --template="navidrome.toml" --destination="/var/lib/$app/navidrome.toml"

#chmod 600 "/var/lib/$app/navidrome.toml"
#chown -R $app:$app "/var/lib/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Version:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
